services:
  postgres:
    restart: always
    environment:
      POSTGRES_USER: ${PROD_DB_USER}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
    volumes:
      - postgres-prod-data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/familyapp
      SPRING_DATASOURCE_USERNAME: ${PROD_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${PROD_DB_PASSWORD}
      APP_CORS_ALLOWED_ORIGINS: https://130.225.170.60

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/ssl:ro
    restart: always

volumes:
  postgres-prod-data: