services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres

  backend:
    image: maven:3.9.12-eclipse-temurin-25
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/familyapp
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS:-http://localhost:4200,http://localhost,http://0.0.0.0}
    # Overwrites any entrypoint to run the dev server
    command: mvn spring-boot:run

  frontend:
    image: node:24-bookworm
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    environment:
      BACKEND_URL: http://backend:8080
    command: sh -c "npm install && npm start -- --host 0.0.0.0 --poll 2000 --proxy-config proxy.conf.mjs"