-- Baseline schema, same to what Hibernate generated before Flyway or ddl-auto=validate fails.
-- cleaned up for PostgreSQL: lowercase snake_case, identity columns, named constraints and an
-- index on every foreign key (PostgreSQL does not create those automatically).

CREATE TABLE family (
    email    varchar(255) NOT NULL,
    password varchar(255),
    CONSTRAINT pk_family PRIMARY KEY (email)
);

CREATE TABLE image (
    id       bigint GENERATED BY DEFAULT AS IDENTITY,
    image    bytea,
    type     varchar(255),
    category varchar(255),
    name     varchar(255),
    CONSTRAINT pk_image PRIMARY KEY (id)
);

CREATE TABLE users (
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    name          varchar(255),
    email         varchar(255),
    role          varchar(255),
    pincode       varchar(255),
    total_points  integer NOT NULL,
    target_points integer NOT NULL,
    family_email  varchar(255),
    image_id      bigint,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT fk_users_family FOREIGN KEY (family_email) REFERENCES family (email),
    CONSTRAINT fk_users_image FOREIGN KEY (image_id) REFERENCES image (id)
);
CREATE INDEX ix_users_family_email ON users (family_email);
CREATE INDEX ix_users_image_id ON users (image_id);

CREATE TABLE task (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    name         varchar(255),
    description  varchar(255),
    points       integer,
    checked      boolean,
    timestamp    timestamp(6),
    repeat_every varchar(255),
    repeat_until timestamp(6),
    image_id     bigint,
    CONSTRAINT pk_task PRIMARY KEY (id),
    CONSTRAINT fk_task_image FOREIGN KEY (image_id) REFERENCES image (id)
);
CREATE INDEX ix_task_image_id ON task (image_id);

CREATE TABLE message (
    id        bigint GENERATED BY DEFAULT AS IDENTITY,
    content   varchar(255),
    timestamp timestamp(6),
    user_id   bigint,
    CONSTRAINT pk_message PRIMARY KEY (id),
    CONSTRAINT fk_message_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX ix_message_user_id ON message (user_id);

CREATE TABLE refresh_tokens (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    token        varchar(255) NOT NULL,
    family_email varchar(255) NOT NULL,
    expires_at   timestamp(6) with time zone NOT NULL,
    user_id      bigint,
    role         varchar(255),
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT uq_refresh_tokens_token UNIQUE (token),
    CONSTRAINT fk_refresh_tokens_family FOREIGN KEY (family_email) REFERENCES family (email),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX ix_refresh_tokens_family_email ON refresh_tokens (family_email);
CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);

-- Join table for User <-> Task. The composite primary key also serves lookups by task_id;
-- the extra index serves lookups by user_id.
CREATE TABLE user_task (
    task_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT pk_user_task PRIMARY KEY (task_id, user_id),
    CONSTRAINT fk_user_task_task FOREIGN KEY (task_id) REFERENCES task (id),
    CONSTRAINT fk_user_task_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX ix_user_task_user_id ON user_task (user_id);
