spring.application.name=backend

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update

# CORS
app.cors.allowed-origins=http://localhost:4200

# JWT
app.jwt.secret=RPFbFvzxzUsa9Z81p9gjDBWZcoJZHhPKZd6FoSxJD9olsFFSSuoKxC2MOPxk
app.jwt.access-token-expiration=60000