spring.application.name=backend
server.forward-headers-strategy=framework

# Datasource
spring.datasource.url=jdbc:postgresql://postgres:5432/familyapp
spring.datasource.username=admin
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update

# CORS
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}

# JWT
app.jwt.secret=RPFbFvzxzUsa9Z81p9gjDBWZcoJZHhPKZd6FoSxJD9olsFFSSuoKxC2MOPxk
app.jwt.access-token-expiration=60000
app.jwt.refresh-token-cookie.secure=${APP_JWT_REFRESH_TOKEN_COOKIE_SECURE:false}
app.jwt.refresh-token-cookie.same-site=${APP_JWT_REFRESH_TOKEN_COOKIE_SAME_SITE:Lax}
app.jwt.refresh-token-cookie.max-age-seconds=${APP_JWT_REFRESH_TOKEN_COOKIE_MAX_AGE_SECONDS:86400}